language: node_js
sudo: false
node_js:
- '6'
install:
- npm install
script:
- npm run build:prd
- npm run lint
- npm run test
deploy:
  provider: npm
  email: hbow1001@gmail.com
  api_key:
    secure: oQO84s0Zdnuvrz7cqnX0lFbmLBIQApkTg49KpN+gnvnYzmMpVw9Y6QtpwGPAfmgdcmEBYmP/E2lW+kLRfTMU2LKAYWIoTSdLJ533M82PRltHR02aBpa64Kaj/PKYUyjDaIFHZsTjUW9kypi3yme1/SEdxPdYyoKn0/4o3WQ9SutLBPz4MPB0jxc5ykoMVrzwK5kTYF9Emm+LXHZPtcsRFoKDdgIMAz+InEvC4rAywHXCsaAyy8x2zGKqn869n1tH+4tsAmjPKY8RUdLgc2n9zPNqQ0HcEXDaeBENx8gE+OcVPh4NB4dJhwKdxpMrkbuTx8SsJ4iUJmVg/rVoge+rOk966FZHF6nxL5yAwaBMwuDEHH1e+FoV+2Ys9z8D/onBuF8kg2iboF/kRe28PcY1ZKGH0pKzPr6wcU83UbcRmCUZl5Wraolxy6XdW9NweZGj6llyWcXgqAUQEj0jmMVUIba8G28lkucrTXELNXqaoWa6gD1J6kJn85FHq4RbiuRBix6+rAyLfSW66dEdz3vMIOvLCVTxpwLyT3eg76u8cJcKIAGs8WzHFILvbCqx5Tn7omSq74OUvhCQCxdULBA9VpkiJQJ/VY094pUtpFQnVYhN2nUi/e4eMkR7Mg1PW5s3dULA9UrUkolbeMvOasF2Ff4n4SsOxNKelapBGndsQdE=
  tag: next
  on:
    tags: false
